defmodule Kaguya.Sitemaps do
  @moduledoc """
  Generates public sitemap XML files.

  The request path serves generated files from R2; this module owns the
  database reads and XML rendering used by the scheduled publisher.
  """

  import Ecto.Query

  alias Kaguya.Characters.Character
  alias Kaguya.Discussions.Post
  alias Kaguya.Lists.List
  alias Kaguya.Producers.Producer
  alias Kaguya.Repo
  alias Kaguya.Reviews.Review
  alias Kaguya.Users.User
  alias Kaguya.VisualNovels
  alias Kaguya.VisualNovels.VisualNovel

  @max_urls_per_sitemap 40_000
  @max_xml_bytes 48_000_000
  @static_paths ~w(/ /browse /lists /members)
  @type_order [:static, :vns, :characters, :producers, :reviews, :vnlists, :discussions]
  @user_content_types [:static, :reviews, :vnlists, :discussions]

  @type t :: :static | :vns | :characters | :producers | :reviews | :vnlists | :discussions

  @doc "All sitemap content types in index order."
  def all_types, do: @type_order

  @doc "Types that change from user-created content."
  def user_content_types, do: @user_content_types

  @doc "Returns true when a public sitemap chunk filename has a known shape."
  def valid_chunk_filename?("sitemap.xml"), do: true

  def valid_chunk_filename?(filename) when is_binary(filename) do
    Regex.match?(
      ~r/\A(static|vnlists|reviews|discussions|characters|vns|producers)-\d+\.xml\z/,
      filename
    )
  end

  def valid_chunk_filename?(_), do: false

  @doc """
  Generate sitemap chunk XML for the selected types.

  Returns a map of filename to XML body. The sitemap index is generated by the
  publisher after it knows which existing R2 chunks are being retained.
  """
  def generate(types \\ @type_order) do
    types
    |> Enum.flat_map(&generate_type/1)
    |> Map.new()
  end

  @doc "Render a sitemap index for chunk filenames."
  def render_index(filenames, lastmod \\ DateTime.utc_now()) do
    urls =
      filenames
      |> Enum.sort_by(&sort_key/1)
      |> Enum.map_join("", fn filename ->
        """
        <sitemap><loc>#{xml_escape(base_url() <> sitemap_path(filename))}</loc><lastmod>#{format_lastmod(lastmod)}</lastmod></sitemap>
        """
      end)

    """
    <?xml version="1.0" encoding="UTF-8"?>
    <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">#{urls}</sitemapindex>
    """
  end

  defp generate_type(:static) do
    entries = Enum.map(@static_paths, fn path -> %{loc: path} end)
    [{"static-0.xml", render_urlset(entries)}]
  end

  defp generate_type(type) when type in @type_order do
    do_generate_type(type, 0, 0, [])
  end

  defp do_generate_type(type, offset, next_chunk, acc) do
    items = list_items(type, offset, @max_urls_per_sitemap)

    if items == [] do
      Enum.reverse(acc)
    else
      files =
        items
        |> entries_for(type)
        |> split_to_limits()
        |> Enum.with_index(next_chunk)
        |> Enum.map(fn {entries, chunk} ->
          {"#{type}-#{chunk}.xml", render_urlset(entries)}
        end)

      do_generate_type(
        type,
        offset + @max_urls_per_sitemap,
        next_chunk + length(files),
        Enum.reverse(files) ++ acc
      )
    end
  end

  defp list_items(:vns, offset, limit) do
    query =
      from(vn in VisualNovel,
        where: is_nil(vn.hidden_at) and not is_nil(vn.slug),
        order_by: [desc: vn.updated_at, desc: vn.id],
        limit: ^limit,
        offset: ^offset,
        select: %{
          id: vn.id,
          slug: vn.slug,
          updated_at: vn.updated_at,
          primary_image_id: vn.primary_image_id,
          temp_image_url: vn.temp_image_url
        }
      )

    Repo.all(query)
    |> Enum.map(fn item ->
      images = VisualNovels.build_image_urls(item)
      Map.put(item, :image_url, images[:medium])
    end)
  end

  defp list_items(:characters, offset, limit) do
    query =
      from(c in Character,
        where: is_nil(c.hidden_at) and not is_nil(c.slug),
        order_by: [desc: c.updated_at, desc: c.id],
        limit: ^limit,
        offset: ^offset,
        select: %{
          id: c.id,
          slug: c.slug,
          updated_at: c.updated_at,
          primary_image_id: c.primary_image_id,
          vndb_image_id: c.vndb_image_id
        }
      )

    Repo.all(query)
    |> Enum.map(fn item ->
      images = VisualNovels.build_character_image_urls(item)
      Map.put(item, :image_url, images[:large])
    end)
  end

  defp list_items(:producers, offset, limit) do
    Producer
    |> where([p], is_nil(p.hidden_at) and not is_nil(p.slug))
    |> order_by([p], desc: p.updated_at, desc: p.id)
    |> limit(^limit)
    |> offset(^offset)
    |> select([p], %{slug: p.slug, updated_at: p.updated_at})
    |> Repo.all()
  end

  defp list_items(:vnlists, offset, limit) do
    List
    |> where([l], l.is_public == true and is_nil(l.hidden_at))
    |> join(:inner, [l], u in User, on: u.id == l.user_id)
    |> where([_l, u], not is_nil(u.username))
    |> order_by([l, _u], desc: l.updated_at, desc: l.id)
    |> limit(^limit)
    |> offset(^offset)
    |> select([l, u], %{
      id: l.id,
      slug: l.slug,
      user_id: l.user_id,
      username: u.username,
      updated_at: l.updated_at
    })
    |> Repo.all()
  end

  defp list_items(:reviews, offset, limit) do
    Review
    |> join(:inner, [r], u in User, on: u.id == r.user_id)
    |> join(:inner, [r], vn in VisualNovel, on: vn.id == r.visual_novel_id)
    |> where(
      [r, u, vn],
      is_nil(r.hidden_at) and is_nil(vn.hidden_at) and not is_nil(u.username) and
        not is_nil(vn.slug)
    )
    |> order_by([r, _u, _vn], desc: r.updated_at, desc: r.id)
    |> limit(^limit)
    |> offset(^offset)
    |> select([r, u, vn], %{
      id: r.id,
      username: u.username,
      vn_slug: vn.slug,
      updated_at: r.updated_at
    })
    |> Repo.all()
  end

  defp list_items(:discussions, offset, limit) do
    Post
    |> join(:left, [p], vn in VisualNovel,
      on: p.category_type == ^:visual_novel and vn.id == p.entity_id
    )
    |> join(:left, [p], pr in Producer,
      on: p.category_type == ^:producer and pr.id == p.entity_id
    )
    |> join(:left, [p], ch in Character,
      on: p.category_type == ^:character and ch.id == p.entity_id
    )
    |> join(:left, [p], u in User, on: p.category_type == ^:user and u.id == p.entity_id)
    |> where(
      [p, vn, pr, ch, u],
      is_nil(p.hidden_at) and is_nil(p.deleted_at) and
        (p.category_type != ^:visual_novel or is_nil(vn.hidden_at)) and
        (p.category_type != ^:producer or is_nil(pr.hidden_at)) and
        (p.category_type != ^:character or is_nil(ch.hidden_at)) and
        (p.category_type != ^:user or not is_nil(u.username))
    )
    |> order_by([p, _vn, _pr, _ch, _u], desc: p.updated_at, desc: p.id)
    |> limit(^limit)
    |> offset(^offset)
    |> select([p, vn, pr, ch, u], %{
      id: p.id,
      short_id: p.short_id,
      slug: p.slug,
      category_type: p.category_type,
      vn_slug: vn.slug,
      producer_slug: pr.slug,
      character_slug: ch.slug,
      target_username: u.username,
      updated_at: p.updated_at
    })
    |> Repo.all()
  end

  defp entries_for(items, :producers) do
    Enum.map(items, &%{loc: "/developer/#{&1.slug}", lastmod: &1.updated_at})
  end

  defp entries_for(items, :vnlists) do
    Enum.map(items, &%{loc: "/@#{&1.username}/list/#{&1.slug}", lastmod: &1.updated_at})
  end

  defp entries_for(items, :reviews) do
    Enum.map(items, &%{loc: "/@#{&1.username}/reviews/#{&1.vn_slug}", lastmod: &1.updated_at})
  end

  defp entries_for(items, :discussions) do
    items
    |> Enum.map(&%{loc: discussion_path(&1), lastmod: &1.updated_at})
    |> Enum.reject(&(&1.loc == "#"))
  end

  defp entries_for(items, :characters) do
    Enum.map(
      items,
      &%{loc: "/character/#{&1.slug}", lastmod: &1.updated_at, image_url: &1.image_url}
    )
  end

  defp entries_for(items, :vns) do
    Enum.map(items, &%{loc: "/vn/#{&1.slug}", lastmod: &1.updated_at, image_url: &1.image_url})
  end

  defp split_to_limits(entries) do
    xml = render_urlset(entries)

    cond do
      byte_size(xml) <= @max_xml_bytes ->
        [entries]

      length(entries) <= 1 ->
        [entries]

      true ->
        {left, right} = Enum.split(entries, div(length(entries), 2))
        split_to_limits(left) ++ split_to_limits(right)
    end
  end

  defp render_urlset(entries) do
    urls = Enum.map_join(entries, "", &render_url/1)

    namespace =
      if Enum.any?(entries, &present?(&1[:image_url])) do
        ~s( xmlns:image="http://www.google.com/schemas/sitemap-image/1.1")
      else
        ""
      end

    """
    <?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"#{namespace}>#{urls}</urlset>
    """
  end

  defp render_url(%{loc: loc} = entry) do
    image = render_image(entry[:image_url])
    lastmod = render_lastmod(entry[:lastmod])

    """
    <url><loc>#{xml_escape(base_url() <> loc)}</loc>#{lastmod}#{image}</url>
    """
  end

  defp render_lastmod(nil), do: ""
  defp render_lastmod(value), do: "<lastmod>#{format_lastmod(value)}</lastmod>"

  defp render_image(url) when is_binary(url) and url != "" do
    "<image:image><image:loc>#{xml_escape(url)}</image:loc></image:image>"
  end

  defp render_image(_url), do: ""

  defp discussion_path(%{short_id: short_id} = item) when is_binary(short_id) do
    case item.category_type do
      :visual_novel when is_binary(item.vn_slug) ->
        "/vn/#{item.vn_slug}/discussions/#{short_id}"

      :producer when is_binary(item.producer_slug) ->
        "/developer/#{item.producer_slug}/discussions/#{short_id}"

      :character when is_binary(item.character_slug) ->
        "/character/#{item.character_slug}/discussions/#{short_id}"

      :user when is_binary(item.target_username) ->
        "/@#{item.target_username}/discussions/#{short_id}"

      _ ->
        "/discussions/p/#{short_id}/#{item.slug || "post"}"
    end
  end

  defp discussion_path(_item), do: "#"

  defp sitemap_path("sitemap.xml"), do: "/sitemap.xml"
  defp sitemap_path(filename), do: "/sitemap/#{filename}"

  defp base_url, do: KaguyaWeb.Endpoint.url() |> String.trim_trailing("/")

  defp format_lastmod(%DateTime{} = dt), do: DateTime.to_iso8601(dt)

  defp format_lastmod(%NaiveDateTime{} = dt),
    do: dt |> DateTime.from_naive!("Etc/UTC") |> DateTime.to_iso8601()

  defp format_lastmod(%Date{} = date), do: Date.to_iso8601(date)
  defp format_lastmod(value), do: value |> to_string() |> xml_escape()

  defp xml_escape(value) do
    value
    |> to_string()
    |> String.replace("&", "&amp;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
    |> String.replace("\"", "&quot;")
    |> String.replace("'", "&apos;")
  end

  defp present?(value), do: is_binary(value) and value != ""

  defp sort_key(filename) do
    case Regex.run(~r/\A([a-z]+)-(\d+)\.xml\z/, filename) do
      [_full, type, chunk] ->
        {Enum.find_index(@type_order, &(Atom.to_string(&1) == type)) || 999,
         String.to_integer(chunk)}

      _ ->
        {999, filename}
    end
  end
end
