// Run with playwright-cli run-code --filename=test/browser/library_controls.js
// Uses a populated local public library; all production actions only change URL filters.
async page => {
  page.setDefaultTimeout(10000)
  const base = "http://localhost:4001"
  const check = (condition, message) => { if (!condition) throw new Error(message) }
  const closed = panel => page.waitForFunction(id => !document.getElementById(id).matches(":popover-open"), panel)
  await page.setViewportSize({width:1440, height:1000})
  await page.goto(`${base}/@superange128/library`)
  await page.locator("[data-phx-main].phx-connected").waitFor()
  await page.locator("#library-sort-popover-desktop-trigger").click()
  await page.locator("#library-sort-popover-desktop-panel").getByRole("button", {name:"Highest rated", exact:true}).click()
  await page.waitForURL(url => url.searchParams.get("sort") === "my-highest-rated")
  await closed("library-sort-popover-desktop-panel")
  await page.locator("#library-rating-popover-trigger").click()
  await page.locator("#library-rating-popover-panel button").filter({has:page.locator('[aria-label="5"]')}).click()
  await page.waitForURL(url => url.searchParams.get("rating") === "5")
  await closed("library-rating-popover-panel")
  check(page.url().includes("sort=my-highest-rated"), "Rating must retain sort")
  await page.screenshot({path:"C:/Users/benze/AppData/Local/Temp/kaguya-library-desktop.png"})
  await page.setViewportSize({width:390, height:844})
  await page.locator("#library-mobile-more-menu-trigger").click()
  const more = page.locator("#library-mobile-more-menu-panel")
  await more.locator("summary").filter({hasText:"Rating"}).click()
  await more.getByRole("button", {name:"All ratings", exact:true}).click()
  await page.waitForURL(url => !url.searchParams.has("rating"))
  await closed("library-mobile-more-menu-panel")
  await page.getByRole("button", {name:"Search library", exact:true}).click()
  const search = page.locator("#library-search-mobile-input")
  await search.fill("Steins")
  await page.waitForURL(url => url.searchParams.get("search") === "Steins")
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "Mobile library must fit viewport")
  await page.screenshot({path:"C:/Users/benze/AppData/Local/Temp/kaguya-library-mobile.png"})
  await page.locator("#library-search-mobile").getByRole("button", {name:"Clear search", exact:true}).click()
  await page.waitForURL(url => !url.searchParams.has("search"))
  if (!(await search.isVisible())) await page.getByRole("button", {name:"Search library", exact:true}).click()
  check(await search.inputValue() === "", "Clearing search must reset the shared input")
  await page.goto(`${base}/dev/ui/style-guide`)
  await page.locator("[data-phx-main].phx-connected").waitFor()
  await page.locator("#demo-filter-trigger").focus()
  await page.keyboard.press("Enter")
  await page.locator("#demo-filter-panel").getByRole("button", {name:"Romance", exact:true}).click()
  await page.getByRole("button", {name:"Remove Romance filter", exact:true}).waitFor()
  await closed("demo-filter-panel")
  await page.getByRole("button", {name:"Remove Romance filter", exact:true}).click()
  await page.getByRole("button", {name:"Remove Romance filter", exact:true}).waitFor({state:"hidden"})
  await page.getByRole("button", {name:"Open dialog", exact:true}).click()
  await page.locator("#demo-dialog[open]").waitFor()
  await page.keyboard.press("Escape")
  await page.locator("#demo-dialog").waitFor({state:"detached"})
  return "Passed: desktop filter dismissals, retained sort, mobile More/search, viewport fit, style-guide selected state and dialog Escape"
}
