import Config

# Serve digested static assets via the manifest generated by `mix assets.deploy`.
# Without this, `static_path/1` falls back to undigested URLs (e.g. /assets/app.css)
# and the browser cache invalidates on every deploy.
config :kaguya, KaguyaWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger,
  level: :info

config :kaguya, :logger, [
  {:handler, :sentry_handler, Sentry.LoggerHandler,
   %{
     config: %{
       # Forward structured fields to Sentry as tags/extras alongside the
       # canonical metadata so dashboards filter on user_id, live_view, etc.
       # Keep this list in sync with the :logger :console :metadata list in
       # config/config.exs.
       metadata: [
         :file,
         :line,
         :request_id,
         :user_id,
         :live_view,
         :live_action,
         :operation,
         :request_path,
         :resource_id,
         :resource_type,
         :critical,
         :event_type,
         :duration_ms,
         :worker,
         :queue,
         :method,
         :status
       ],
       # `:cowboy` / `:bandit` — default; avoid double-report with PlugCapture.
       # `:otp` — Phoenix LiveView uses `:telemetry.span/3` which re-raises
       # exceptions; the resulting GenServer crash produces an OTP/SASL
       # crash report that's already covered by our
       # `[:phoenix, :live_view, *, :exception]` telemetry handler with
       # first-class tags (see `Kaguya.Observability.Telemetry.handle_live_view_exception/4`).
       # Excluding `:otp` here keeps Sentry quota clean. Crash reports still
       # land in Axiom (which doesn't filter by domain) for forensics.
       excluded_domains: [:cowboy, :bandit, :otp],
       capture_log_messages: true,
       # Only log errors to Sentry
       level: :error,
       # Prevent spam
       rate_limiting: [max_events: 10, interval: 1_000]
     }
   }},
  {:handler, :axiom_handler, Kaguya.Observability.AxiomLogHandler,
   %{
     config: %{
       # Ship warnings and above: SLOW_QUERY, POOL_WAIT, SLOW_REQ, etc.
       level: :warning
     }
   }}
]

# DSN / environment_name / release move to config/runtime.exs so they can
# be driven by env vars (SENTRY_DSN, SENTRY_ENVIRONMENT, SENTRY_RELEASE).
# Compile-time-only knobs (source context paths) stay here.
config :sentry,
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]

# CORS
config :kaguya, :cors_origins, [
  "https://kaguya.io",
  "https://kaguyabooks.com",
  "https://vn.kaguya.io"
]

# Meili indexing
config :kaguya, :enable_meili_indexing, true

# Enable origin header protection since this is prod API behind Cloudflare
config :kaguya, :protect_origin_header, true

# ---------------------------------------------------------------------------
# DO NOT add `force_ssl:` to KaguyaWeb.Endpoint here.
#
# Cloudflare terminates TLS at the edge and forwards to the Hetzner origin
# over HTTP. Phoenix's `force_ssl` plug then sees an http:// request and
# issues a 301 to https:// — even with `rewrite_on: [:x_forwarded_proto]`,
# the shortcut runs after the redirect decision in some proxy chains.
#
# 301 on a POST drops the request body. This previously broke the old
# Next.js SSR render path; LiveView survived because its WebSocket upgrade
# was already complete on initial load.
#
# HTTPS enforcement is handled by Cloudflare's "Always Use HTTPS" page
# rule. If you ever need it at the app layer, add `Plug.RewriteOn` as a
# real plug in the endpoint pipeline ahead of any redirect logic — don't
# rely on the `rewrite_on:` shortcut inside `force_ssl:`.
#
# Incident: 2026-05-15 — bisected to commit `3ff009f2`; see
# docs/operations/observability/incident-response.md (Known signatures table).
# ---------------------------------------------------------------------------
