defmodule Kaguya.Recommendations.UserVnRecommendation do
  @moduledoc """
  Per-user VN recommendation row. Generated by `Kaguya.Recommendations.GenerateWorker`
  via the EASE pipeline and served through the `Recommendations` context.
  """
  use Kaguya.Schema

  alias Kaguya.Users.User
  alias Kaguya.VisualNovels.VisualNovel

  @primary_key false
  @foreign_key_type :binary_id

  schema "user_recommendations" do
    belongs_to :user, User, primary_key: true
    belongs_to :visual_novel, VisualNovel, primary_key: true

    field :score, :float
    field :ease_score, :float
    field :rank, :integer
    # Top-3 "because you liked" attributions paired with each source VN's
    # raw positive contribution to `score`. Ordered by `contribution`
    # desc. See the migration for why contributions live here (and not
    # derived client-side from `score` alone).
    field :reasons, {:array, :map}, default: []
    # Sum of all positive per-item contributions to `score`. Denominator
    # for the tooltip's per-reason percentage (`contribution / total_positive`).
    field :total_positive_contribution, :float
    field :model_version, :string
    field :generated_at, :utc_datetime_usec
  end

  def changeset(rec, attrs) do
    rec
    |> cast(attrs, [
      :user_id,
      :visual_novel_id,
      :score,
      :ease_score,
      :rank,
      :reasons,
      :total_positive_contribution,
      :model_version,
      :generated_at
    ])
    |> validate_required([
      :user_id,
      :visual_novel_id,
      :score,
      :ease_score,
      :rank,
      :model_version,
      :generated_at
    ])
    |> assoc_constraint(:user)
    |> assoc_constraint(:visual_novel)
    |> unique_constraint([:user_id, :visual_novel_id],
      name: :user_vn_recommendations_pkey
    )
  end
end
